variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

stages:
  - testing
  - deploy

# -------------
# Testing
# -------------
test_ui:
  stage: testing
  image: docker/compose:1.29.2
  services:
    - docker:20.10.17-dind
  variables:
    COMPOSE_FILE: "microservices/src/docker-compose.yml:microservices/src/search_engine_ui/tests/docker-compose-tests.yml"
  script:
    - docker-compose up -d ui
    - docker exec -w / src_ui_1 pip install -r /ui/requirements-test.txt
    - docker exec -w / src_ui_1 coverage run -m unittest discover -s tests/
    - docker exec -w / src_ui_1 coverage report --include ui/ui.py
    - docker-compose down

test_crawler:
  stage: testing
  image: docker/compose:1.29.2
  services:
    - docker:20.10.17-dind
  variables:
    COMPOSE_FILE: "microservices/src/docker-compose.yml:microservices/src/search_engine_crawler/tests/docker-compose-tests.yml"
  script:
    - docker-compose up -d crawler
    - docker exec -w / src_crawler_1 ls -l / /crawler
    - docker exec -w / src_crawler_1 pip install -r /crawler/requirements-test.txt
    - docker exec -w / src_crawler_1 coverage run -m unittest discover -s tests/
    - docker exec -w / src_crawler_1 coverage report --include crawler/crawler.py
    - docker-compose down

deploy_prod:
  stage: deploy
  image: groben/terransible:1.3
  before_script:
    - mkdir $HOME/yandex-cloud && echo $terraform_key > $HOME/yandex-cloud/terraform-key.json
    - mkdir $HOME/.ssh && cp $otus_project $HOME/.ssh/otus-project && chmod 600 $HOME/.ssh/otus-project
    - cp keys/otus-project.pub $HOME/.ssh/ && chmod 644 $HOME/.ssh/otus-project.pub
    - chmod 755 microservices/ansible/
    - cp microservices/terraform/provider_install.tfrc $HOME/.terraformrc
    - chmod 664 $HOME/.terraformrc
  script:
    - terraform -v
    - ansible --version
    - cd microservices/ansible
    - ansible-galaxy install -r requirements.yml
    - ansible-playbook playbooks/app.yml --private-key=$HOME/.ssh/otus-project -e tf_bucket_access_key=$tf_bucket_access_key -e tf_bucket_secret_key=$tf_bucket_secret_key
    - cd -
    - DYNAMIC_ENVIRONMENT_URL=$(cat microservices/ansible/environments/prod/inventory | awk '/app-host/ {print $2}' | awk -F = '{print "http://"$2".nip.io"}')
    - echo "DYNAMIC_ENVIRONMENT_URL=$DYNAMIC_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env
  environment:
    name: production
    url: $DYNAMIC_ENVIRONMENT_URL
  when: manual